
AWSTemplateFormatVersion: 2010-09-09
Description: 4.1.1 Lab Ryan
Resources:
  EC2VPCCB:
    Type: 'AWS::EC2::VPCCidrBlock'
    Properties:
      CidrBlock: 172.0.0.1/16
      Tags: 
      - Key: "user"
        Value: "ryan.lewon.labs"
      - Key: "stelligent-u-lesson"
        Value: "4"
      - Key: "stelligent-u-lab"
        Value: "4.1.1"
  EC2Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties: 
      CidrBlock: 172.2.0.1/24
      Tags: 
      - Key: "user"
        Value: "ryan.lewon.labs"
      - Key: "stelligent-u-lesson"
        Value: "4"
      - Key: "stelligent-u-lab"
        Value: "4.1.1"
  EC2Igw:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags: 
      - Key: "user"
        Value: "ryan.lewon.labs"
      - Key: "stelligent-u-lesson"
        Value: "4"
      - Key: "stelligent-u-lab"
        Value: "4.1.1"
Outputs:
  VPCCBOutput:
    Description: EC2 VPC ID Output
    Value: !Ref EC2VPCCB
    Export:
      Name: EC2VPCCB-Id
  EC2SubnetOutput:
    Description: EC2 VPC Subnet ID
    Value: !Ref EC2Subnet
    Export:
      Name: EC2Subnet-Id
