
AWSTemplateFormatVersion: 2010-09-09
Description: 4.1.1 Lab Ryan
Parameters:
  VPCCidr:
    Type: String
    Default: 10.0.0.1/16
  EC2Cidr:
    Type: String
    Default: 10.0.2.1/24
Resources:
  EC2VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsSupport: false
      EnableDnsHostnames: false
      Tags:
        - Key: Name
          Value: "ryan.lewon.labs-vpc"
        - Key: user
          Value: ryan.lewon.labs
        - Key: stelligent-u-lesson
          Value: 4
        - Key: stelligent-u-lab
          Value: 4.1.2
  EC2Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref EC2Cidr
      VpcId: 
        Ref: EC2VPC
  EC2Igw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: user
          Value: ryan.lewon.labs
        - Key: stelligent-u-lesson
          Value: 4
        - Key: stelligent-u-lab
          Value: 4.1.2
  EC2IgwAtt:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref EC2Igw
      VpcId: !Ref EC2VPC
  RTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref EC2VPC
      Tags:
        - Key: Name
          Value: "ryan.lewon.labs-route-table"
        - Key: user
          Value: ryan.lewon.labs
        - Key: stelligent-u-lesson
          Value: 4
        - Key: stelligent-u-lab
          Value: 4.1.2
  PRoute:
    Type: AWS::EC2::Route
    DependsOn: EC2IgwAtt
    Properties:
      RouteTableId: !Ref RTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref EC2Igw
  RTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RTable
      SubnetId: !Ref EC2Subnet
Outputs:
  VPCCBOutput:
    Description: EC2 VPC ID Output
    Value: !Ref EC2VPC
    Export:
      Name: ryan-lewon-labs-vpcid
  EC2SubnetOutput:
    Description: EC2 VPC Subnet ID
    Value: !Ref EC2Subnet
    Export:
      Name: ryan-lewon-labs-subnet-id
