AWSTemplateFormatVersion: 2010-09-09
Description: IAM Template created and limits to readonly IAM resources
Resources:
  IAMPolicy:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::324320755747:user/ryan.lewon.labs
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess