AWSTemplateFormatVersion: 2010-09-09
Description: 3.1.3 duplicated IAM Policy
Resources:
  IAMRORole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::324320755747:user/ryan.lewon.labs'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
Outputs:
  ReadOnlyRoleARN:
    Value: !GetAtt IAMRORole.Arn

